---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset"
  )
```

## Results: Distribution plot

```{r}
tar_read(plot_distributions)
```

## Preparing the data

```{r}
lipidomics |>
  count(code, metabolite) |>
  filter(n > 1)
```

```{r}
lipidomics |>
  group_by(pick(-value)) |>
  summarise(value = mean(value), .groups = "keep") |>
  ungroup()
```

```{r}
```

## Running multiple models

```{r}
just_cholesterol <- lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()


lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_all_models()
```

## Exercise 21. 5

```{r}
lipidomics |>
  group_split(metabolite) |>
  map(preprocess) |>
  map(fit_all_models) |>
  list_rbind()
```

## Figure of model estimates

```{r}
model_results <- tar_read(model_results)
```

```{r}
model_results |>
  dplyr::filter(term == "value", std.error <= 2, estimate <= 5) |>
  dplyr::select(metabolite, model, estimate, std.error) |>
  ggplot2::ggplot(aes(
    x = estimate,
    y = metabolite,
    xmin = estimate - std.error,
    xmax = estimate + std.error
  )) +
  ggplot2::geom_pointrange() +
  ggplot2::geom_vline(xintercept = 1, linetype = "dashed") +
  ggplot2::facet_grid(cols = ggplot2::vars(model))
```

```{r}


# It should be used like this:
create_plot_model_results(model_results)
```

## Model results

```{r}
tar_read(plot_model_results)
```

## Appendix

```{r}
tar_read(model_results) |>
  knitr::kable(
    caption = "Model results for all metabolites"
  )
```
